import { StyleSheet } from 'react-native';
import { backgroundColor, inputTextColor, lightTextColor, mainColor, textColorLight, absoluteWidth, absoluteHeight } from './Main';

export const styles = StyleSheet.create({
    container: {
        marginVertical: 10,
        width: 332 * absoluteWidth,
        height: 138 * absoluteHeight,
        backgroundColor: backgroundColor,
        shadowColor: '#000',
        shadowOffset: { width: 2, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 5, 
        borderRadius: 11,
        flexDirection: 'row',
    },
    imageStyle: {
        postion: 'absolute',
        left:0,
        width: 168 * absoluteWidth,
        height : 138 * absoluteHeight,
        borderRadius: 11,
    },
    textContainer: {
        position: 'absolute',
        left:  183 * absoluteWidth,
        width: 143 * absoluteWidth,
    },
    title: {
        position: 'absolute',
        top: 14 * absoluteHeight,
        color: inputTextColor,
        fontSize: 18,
        fontFamily: 'Poppins',
        fontWeight: '600',
    },
    locationContainer: {
        position: 'absolute',
        top: 46 * absoluteHeight,
        flexDirection: 'row',
        alignItems: 'flex-start',
    },
    locationText: {
        color: textColorLight,
        fontSize: 11,
        fontFamily: 'Nunito',
        fontWeight: '400',
    },
    locationIcon: {
        width: 13,
        height: 14,
        marginRight: 5,
    },
    appointmentTimeIcon: {
        width: 13,
        height: 14,
        marginRight: 5,
    },
    description: {
        position: 'absolute',
        top: 69 * absoluteHeight,
        color: lightTextColor,
        fontSize: 10,
        fontFamily: 'Poppins',
        fontWeight: '400',
        lineHeight: 18,
    },
    ratingContainer: {
        position: 'absolute',
        borderRadius: 50,
        top: 5 * absoluteHeight,
        left: 5 * absoluteWidth,
        width: 67 * absoluteWidth,
        height: 23 * absoluteHeight,
        backgroundColor: mainColor,
        zIndex: 10,
    },
    ratingIconContainer: {
        position: 'absolute',
        top: 1.4 * absoluteHeight,
        left: 1 * absoluteWidth,
        width: 20 *  absoluteWidth,
        height: 20 * absoluteHeight,
        borderRadius: 22,
        backgroundColor: backgroundColor,
        zIndex: 20,
    },
    ratingIcon: {
        width: 11 *  absoluteWidth,
        height: 11 * absoluteHeight,
        backgroundColor: backgroundColor,
    },
    ratingText: {
        position: 'absolute',
        left: 25 * absoluteWidth,
        top: 4 * absoluteHeight,
        color: backgroundColor,
        fontSize: 13.05, 
        fontFamily: 'Mazzard', 
        fontWeight: '500',
    },
    numberOfVotes: {
        position: 'absolute',
        left: 46 * absoluteWidth,
        top: 7.4 * absoluteHeight,
        color: backgroundColor,
        fontSize: 8.12, 
        fontFamily: 'Mazzard', 
        fontWeight: '500',
    },
});
