#Database configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${DATASOURCE_HOST:172.233.245.119}:3306/easy_barber_stagging_heavy
spring.datasource.username=${DATASOURCE_USERNAME:teamsantos}
spring.datasource.password=${DATASOURCE_PWD:PMnLZYu4jVfT-U2}
spring.datasource.driver-class-name=${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
jwt.secretKey=${JWT_SECRET_KEY:1HxR4lXMrn5Zd2GUykFcLw6ujEAQpBJ3GpilqZplnYb_vbP-7JVQBKhAdyQs-wkEBoOywiUwmOzth-1mrXLBGA}
jwt.expirationTime=${JWT_EXPIRATION_TIME:2592000000}
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
logging.level.org.springframework.security=DEBUG
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# Application version
app.data.version=1.0.0
teamsantos.istest=true
teamsantos.istestheavy=false

# Twilio configuration
twilio.account-sid=${TWILIO_SID:ACfe53393478f23e6bc18623d7ba8c3f2a}
twilio.auth-token=${TWILIO_TOKEN:023282afa571e9afdaf4d158e652fe7e}
twilio.sender-id=${TWILLIO_SENDER_ID:TeamSantos}

# Scheduler chrono configuration
scheduler.appointments.reminder.enabled=true
%dev.scheduler.appointments.reminder.enabled=false
scheduler.appointments.reminder = ${SCHEDULE_APPOINTMENT_REMINDER_CHRONO:0 */10 * * * *}

# CORS allowed origins
cors.allowed.origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000, http://teamsantos.work, https://teamsantos.work, http://www.teamsantos.work, https://www.teamsantos.work}

server.port:8080

aws.accessKeyId=AKIAVY2PGQ7E4TBJTY7N
aws.secretKey=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
aws.s3.bucket=arn:aws:s3:::bucket-barber-staging
aws.s3.region=eu-south-2
