spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:172.233.245.119}:3306/easy_barber_stagging
spring.datasource.username=teamsantos
spring.datasource.password=PMnLZYu4jVfT-U2
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
jwt.secretKey=${JWT_SECRET_KEY:1HxR4lXMrn5Zd2GUykFcLw6ujEAQpBJ3GpilqZplnYb_vbP-7JVQBKhAdyQs-wkEBoOywiUwmOzth-1mrXLBGA}
jwt.expirationTime=${JWT_EXPIRATION_TIME:2592000000}
jwt.hashingAlgorithm=${JWT_HASHING_ALG:HS512}