spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:172.233.245.119}:3306/easy_barber_stagging
spring.datasource.username=teamsantos
spring.datasource.password=PMnLZYu4jVfT-U2
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
jwt.secretKey=${JWT_SECRET_KEY:m3Z9xfx_6Kyv2D0s7l79xgDKQyu-1zEA-wOEu3Us3_LqIIIYTEuM6q9Slhcmtc2oYChwdQC2ohcWck3KEtO2-Q}
jwt.expirationTime=${JWT_EXPIRATION_TIME:2592000000}
jwt.hashingAlgorithm=${JWT_HASHING_ALG:HmacSHA512}