# Use the official OpenJDK 17 as a base image
FROM eclipse-temurin:17-jdk-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file of your Spring Boot application into the container
# (Make sure to replace `your-app.jar` with the actual name of your JAR file)
COPY ../target/easybarber-0.0.1-SNAPSHOT.jar /app/easybarber.jar

# Expose the port your Spring Boot application is running on (default is 8080)
EXPOSE 8080

# Run the application using java -jar
ENTRYPOINT ["java", "-jar", "/app/easybarber.jar"]