import { StyleSheet } from 'react-native';
import { useTheme } from './ThemeContext';

export const getStyles = () => {
    const theme = useTheme();
    return StyleSheet.create({
        container: {
            width: theme.dimensions.input.width,
            height: theme.dimensions.input.height,
        },
        weekdaysContainer: {
            alignSelf: 'center',
            width: 366 * theme.dimensions.absoluteWidth,
            height: 79 * theme.dimensions.absoluteHeight,
            flexDirection: 'row',
            justifyContent: 'space-between',
            marginTop: 10 * theme.dimensions.absoluteHeight,
        },
        weekdayContainer: {
            width: 48 * theme.dimensions.absoluteWidth,
            height: 79 * theme.dimensions.absoluteHeight,
            backgroundColor: theme.colors.backgroundColor,
            borderRadius: 10 * theme.dimensions.absoluteWidth,
            alignItems: 'center',
            justifyContent: 'center',
        },
        weekdaySelected: {
            backgroundColor: theme.colors.imageBackground,
        },
        weekdayText: {
            color: theme.colors.text.main,
            fontSize: theme.fonts.size._15,
            fontFamily: 'Mazzard',
            fontWeight: "600",
        },
        weekdayTextSelected: {
            color: theme.colors.mainColor,
            fontSize: theme.fonts.size._17,
            fontWeight: "900",
        },
        timeSheetItemContainer: {
            width: 327 * theme.dimensions.absoluteWidth,
            height: 64 * theme.dimensions.absoluteHeight,
            backgroundColor: theme.colors.mainColor,
            borderRadius: 10 * theme.dimensions.absoluteWidth,
            alignSelf: 'center',
            alignItems: 'center',
            justifyContent: 'center',
        },
        timeSheetItemIcon: {
            alignSelf: 'center',
            justifyContent: 'center',
            width: 26 * theme.dimensions.absoluteWidth,
        },
        timeSheetItemSmallIcon: {
            alignSelf: 'center',
            justifyContent: 'center',
            width: 16 * theme.dimensions.absoluteWidth,
        },
        timeSheetItemInnerContainer: {
            flexDirection: 'row',
            width: 137 * theme.dimensions.absoluteWidth,
            height: 26 * theme.dimensions.absoluteHeight,
            alignSelf: 'center',
            justifyContent: "space-evenly",
            alignItems: 'center',
        },
        timeSheetItemTextContainer: {
            flexDirection: 'row',
            width: "100%",
            justifyContent: 'center',
            alignSelf: 'center',
            alignItems: 'center',
        },
        timeSheetItemText: {
            color: theme.colors.text.alt,
            fontSize: theme.fonts.size._14,
            fontFamily: 'Mazzard',
            fontWeight: "900",
        },
        timeSheetListContainer: {
            width: 327 * theme.dimensions.absoluteWidth,
            minHeight: 217 * theme.dimensions.absoluteHeight,
            maxHeight: 417 * theme.dimensions.absoluteHeight,
            alignSelf: 'center',
        },
        addButton: {
            alignSelf: 'center',
            alignItems: 'center',
            maxWidth: 56 * theme.dimensions.absoluteWidth,
            maxHeight: 56 * theme.dimensions.absoluteWidth,
            padding: 15 * theme.dimensions.absoluteWidth,
            borderRadius: 28 * theme.dimensions.absoluteWidth,
        },
        timeSelectContainer: {
            width: 328 * theme.dimensions.absoluteWidth,
            height: 219 * theme.dimensions.absoluteHeight,
            maxHeight: 262 * theme.dimensions.absoluteHeight,
            alignSelf: 'center',
            justifyContent: 'center',
            alignItems: 'center',
        },
        timeSelectText: {
            color: theme.colors.text.main,
            fontSize: theme.fonts.size._16,
            fontFamily: 'Mazzard',
            fontWeight: "900",
            position: 'absolute',
            top: 5 * theme.dimensions.absoluteHeight,
            left: 5 * theme.dimensions.absoluteWidth,
        },
        timeSelectButton: {
            width: 190 * theme.dimensions.absoluteWidth,
            height: 56 * theme.dimensions.absoluteHeight,
            backgroundColor: theme.colors.mainColor,
            borderRadius: 30 * theme.dimensions.absoluteWidth,
            alignItems: 'center',
            justifyContent: 'center',
            alignSelf: 'center',
            position: 'absolute',
            top: 134 * theme.dimensions.absoluteHeight,
        },
        timeSelectButtonText: {
            color: theme.colors.text.alt,
            fontSize: theme.fonts.size._18,
            fontFamily: 'Mazzard',
            fontWeight: "900",
        },
        timeSelectItemContainer: {
            width: 328 * theme.dimensions.absoluteWidth,
            height: 88 * theme.dimensions.absoluteHeight,
            backgroundColor: theme.colors.imageBackground,
            borderRadius: 10 * theme.dimensions.absoluteWidth,
            flexDirection: 'row',
            justifyContent: 'space-evenly',
            alignSelf: 'center',
            alignItems: 'center',
            position: 'absolute',
            top: 30 * theme.dimensions.absoluteHeight,
        },
        timeSelectItem: {
            width: 71 * theme.dimensions.absoluteWidth,
            height: 43 * theme.dimensions.absoluteHeight,
            alignItems: 'center',
            justifyContent: 'center',
        },
        timeSelectItemTextTop: {
            alignSelf: 'flex-start',
            color: theme.colors.text.lightGray,
            fontSize: theme.fonts.size._14,
            fontFamily: 'Mazzard',
            fontWeight: "900",
        },
        timeSelectItemTextBottom: {
            alignSelf: 'flex-start',
            color: theme.colors.text.main,
            fontSize: theme.fonts.size._18,
            fontFamily: 'Mazzard',
            fontWeight: "900",
        },
        icon: {
            zIndex: 3,
            elevation: 2,
            borderWidth: 1,
            borderRadius: 50 * theme.dimensions.absoluteWidth,
            padding: 10 * theme.dimensions.absoluteWidth,
            height: 50 * theme.dimensions.absoluteWidth,
            width: 50 * theme.dimensions.absoluteWidth,
            alignItems: "center",
            justifyContent: "center",
            fontSize: 24 * theme.dimensions.absoluteWidth,
        },
        redIcon: {
            backgroundColor: theme.colors.mainColor,
            borderColor: theme.colors.mainColor,
        },
    });
}
