name: Docker Build and Push (staging)

on:
  push:
    branches:
      - main
    paths:
          - 'Server/**'
          - '.github/workflows/**'
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Build with Maven
        run: |
          cd Server
          mvn clean package -DskipTests
      - name: Prepare Docker build
        run: |
          mkdir -p Server/Docker/target
          cp Server/target/easybarber-0.0.1-SNAPSHOT.jar Server/Docker/target/
      - name: Build Docker image
        run: |
          cd Server/Docker
          docker build -f Dockerfile.stage -t easy-barber:latest .
        env:
          DOCKER_BUILDKIT: 1

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 --rm easy-barber:latest