name: Run tests for pull request
on:
  pull_request:
    branches:
      - main
    paths:
      - 'Server/**'
      - '.github/workflows/**'

permissions:
  pull-requests: write
  issues: write

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      
      - name: Read and sanitize the report content
        id: read_report
        run: |
          REPORT_CONTENT=$(cat report.md)
          # Sanitize by removing angle brackets
          SANITIZED_CONTENT=$(echo "$REPORT_CONTENT" | sed 's/[<>]//g')
          echo "::set-output name=report::$SANITIZED_CONTENT"
        
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: 'Thank you for your pull request!'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
