name: Run tests for pull request
on:
  pull_request:
    branches:
      - main
    paths:
      - 'Server/**'
      - '.github/workflows/**'
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      
      - name: Build with Maven
        run: |
          cd Server
          mvn clean install -DskipTests -X
          mvn surefire-report:report
      
      - name: Run Python script to generate report
        run: |
          python3 createTestReport.py
      
      - name: Read the report content
        id: read_report
        run: |
          REPORT_CONTENT=$(cat report.md)
          echo "report=${REPORT_CONTENT}" >> $GITHUB_OUTPUT
        
      - name: Post report as PR comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.read_report.outputs.report }}
